config/routes.rb
Rails.application.routes.draw do

  resources :sessions,only:[:new,:create,:destroy]
  resources :users, only: [:new,:create,:show]
  resources :records do
    collection do
      post :confirm
      get :top
    end
  end
  resources :favorites, only:[:create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  validates :title,:content, length: { in: 1..140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
  uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :record, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_records, through: :favorites,source: :record
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(record_id: params[:record_id])
    redirect_to records_url, notice: "#{favorite.record.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to records_url, notice: "#{favorite.record.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  include SessionsHelper
  before_action :check_login
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user,only: [:edit, :update, :destroy]

  def index
    @records = Record.all
  end

  def new
    if params[:back]
      @record = Record.new(record_params)
    else
      @record = Record.new
    end
  end

  def create
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    if @record.save
      RecordMailer.contact_mail(@record).deliver
      redirect_to records_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @record = Record.find(params[:id])
    @user = @record.user
    @favorite = current_user.favorites.find_by(record_id: @record.id)
  end

  def edit
    @record = Record.find(params[:id])
  end

  def update
    @record = Record.find(params[:id])
    if @record.update(record_params)
      redirect_to records_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @record.destroy
    redirect_to records_path, notice:"ブログを削除しました！"
  end

  def confirm
    @record = Record.new(record_params)
    @record.user_id = current_user.id
    render :new if @record.invalid?
  end

  private

  def record_params
    params.require(:record).permit(:title, :content, :image, :image_cache)
  end

  def set_record
    @record = Record.find(params[:id])
  end

  def check_login
    if !logged_in?
      redirect_to new_session_path
    end
  end

  def ensure_correct_user
    @record = Record.find_by(id:params[:id])
    if @record.user_id != @current_user.id
      flash[:notice] = "権限がありません"
      redirect_to(records_path)
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      render template: 'records/top'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_records = @user.favorite_records
  end

  private

  def user_params
    params.require(:user).
    permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/records_helper.rb
module RecordsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_records_path
    elsif action_name == 'edit'
      record_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      current_user.present?
    end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width">
  </head>

  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">Bootstrap</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/records/top">top</a></li>
            <li><a href="/records">index</a></li>
            <li><a href="/records/new">new</a></li>
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Login", new_session_path %></li>
            <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>

  <footer>
    <p>2018-05 佐藤邦彦</p>
  </footer>

</html>

app/views/records/_form.html.erb
<%= form_with(model: @record, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= @record.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @record.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>
  <div class="content">
    <%= form.label :content %>
    <br>
    <%= form.text_field :content %>
  </div>
  <div class="image">
    <%= form.label :image %>
    <%= image_tag(@record.image.url) if @record.image.url %>
    <%= form.file_field :image, class: 'file' %>
  </div>

  <%= form.submit "投稿する", class: 'btn btn-default' %>
<% end %>

<br>
<%= link_to "ブログ一覧画面にもどる", records_path, class: 'btn btn-default'  %>

app/views/records/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @record, url: records_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @record.title %></p>
  <p>本文:<%= @record.content %></p>
  <p>画像<%= image_tag @record.image %></p>
  <%= form.hidden_field :image_cache %>
  <%= form.submit  " 投稿する", :class => 'btn btn-warning'%>
<% end %>

<%= form_with(model: @record, url: new_record_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' ,class: 'btn btn-default' %>
<% end %>

app/views/records/edit.html.erb
  <h2>ブログを編集する</h2>

  <%= render 'form' %>

app/views/records/index.html.erb
<h1>ブログ一覧</h1>

<%= link_to '新しくブログを投稿する', new_record_path , class: 'btn btn-default'  %>

<div class="container">
  <p>タイトル  内容  投稿者</p>

<table>
  <div class ="row">
    <% @records.each do |record| %>
      <tr class="col-xs-12 col-md-6">
        <td width="50"><%= record.title %></td>
        <td width="50"><%= record.content %></td>
        <td width="50"><%= record.user.name %></td>
        <td><%= link_to '詳細を確認する', record_path(record.id) %></td>
        <% if record.user_id == current_user.id %>
          <td><%= link_to "ブログを編集する", edit_record_path(record.id) %></td>
          <td><%= link_to 'ブログを削除する', record_path(record.id), method: :delete , data: { confirm: '本当に編集していいですか？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </div>
</table>
</div>

app/views/records/new.html.erb
  <h2>ブログを作成する</h2>

  <%= render 'form' %>

app/views/records/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @record.title %></p>
<p>内容: <%= @record.content %></p>
<p>投稿者: <%= @user.name %></p>
<p>画像: <%= image_tag @record.image %></p>
<% unless @record.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(record_id: @record.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<br>
<br>
<%= link_to ' 投稿一覧へ', records_path , class: 'btn btn-info'%>

app/views/records/top.html.erb
<article>
  <div class="container">
    <div class="contents">
      <%= image_tag 'blog.jpg', :size =>'480x320'%>
    </div>
    <div class="topic">
      <ul class="row">
          <li class="col-xs-12 col-md-4"> このアプリは投稿を保存・閲覧・削除出来ます</li>
          <li class="col-xs-12 col-md-4">レスポンシブデザインで作られています</li>
      </ul>
    </div>
  </div>
</article>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :email %>
  <%= f.email_field :email %>
<br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
<br>
  <div class ="image">
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image.url %>
    <%= f.file_field :image, class: "record_image" %>
    <%= f.hidden_field :image_cache %>
  </div>

  <%= f.submit "Create my account" , :class => 'btn btn-default'%>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<p>ユーザー画像: <%= image_tag @user.image %></p>

<p>お気に入り一覧</p>
  <% @favorites_records.each do |favorite_record| %>
  <table>
    <tr>
      <td>タイトル:<%= favorite_record.title %></td>
      <td>内容:<%= favorite_record.content %></td>
      <td>投稿者:<%= favorite_record.user.name%>
      <td><%= link_to '詳細を確認する', record_path(favorite_record.id) %></td>
    </tr>
    <table>
  <% end %>
<br>
<p><%= link_to '投稿一覧へ', records_path, class: 'actions' %></p>